apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-node-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-application # Ensure this matches your deployment name
  minReplicas: 2      # Minimum number of pods
  maxReplicas: 10     # Maximum number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu       # Metric type (cpu or memory)
        target:
          type: Utilization
          averageUtilization: 50 # Target average CPU utilization percentage
